spring:
    datasource:
      url: jdbc:mysql://localhost:3306/alpha
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
#    thymeleaf:
#        cache: false
#        mode: LEGACYHTML5



mybatis:
  type-aliases-package: com.pjb.entity
  mapper-locations: classpath*:com.pjb.mapper/*.xml


mapper.mappers: tk.mybatis.springboot.util.MyMapper
mapper.not-empty: true
mapper.identity: MYSQL
